In [3]:
import json
import pandas as pd

with open("..\Raw Data\data-instagram.json") as file:
    data = json.load(file)

type(data)

dict

In [6]:
data.keys()

dict_keys(['media', 'label_values', 'fbid'])

In [12]:
advertisers = data["label_values"][0]["vec"]
type(advertisers)

list

In [13]:
pd.DataFrame(data=advertisers)

                          value
0                        Indeed
1                   NOCAP, Inc.
2            MediaCom Melbourne
3                  Brother Sews
4                    SharkNinja
...                         ...
4778                Royle Media
4779               Judge & Jury
4780                 Fox 8 News
4781  Prospector Baseball Group
4782            Kleen Nutrition

[4783 rows x 1 columns]

In [15]:
df = pd.DataFrame(advertisers)
df.head()

                value
0              Indeed
1         NOCAP, Inc.
2  MediaCom Melbourne
3        Brother Sews
4          SharkNinja

In [16]:
df = df.rename(
        columns = {"value": "advertiser_name"}
    )